[package]
name = 'kernel'
version = '0.1.0'
edition = '2024'
authors = ['Mako', 'JayAndJef']

[[bin]]
name = 'kernel'
test = false
bench = false

[dependencies]
bootloader_api = '0.11.8'
embedded-graphics = '0.8.1'
log = { version = '0.4.22', default-features = false }
bootloader-x86_64-common = '0.11.8'
conquer-once = { version = '0.4.0', default-features = false }
spin = "0.9.8"
