name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-none
        
    - name: Build kernel
      run: make

    - name: Upload iso image artifact
      uses: actions/upload-artifact@v4
      with:
        name: locos.iso
        path: locos.iso

        
