name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install xorriso
      run: sudo apt-get install -y xorriso
    
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-06-20
        targets: x86_64-unknown-none
        components: rust-src
        
    - name: Build kernel
      run: make

    - name: Upload iso image artifact
      uses: actions/upload-artifact@v4
      with:
        name: locos.iso
        path: locos.iso

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: install xorriso
      run: sudo apt-get install -y xorriso

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-06-20
        targets: x86_64-unknown-none
        components: rust-src

    - name: run tests
      run: make test

        
