name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-unknown-none
        
    - name: Build kernel
      run: make kernel
      
    - name: Build bootimage
      run: make bootimage

    - name: Upload uefi image artifact
      uses: actions/upload-artifact@v2
      with:
        name: uefi-image
        path: bootimage/target/debug/uefi.img
    
    - name: Upload bios image artifact
      uses: actions/upload-artifact@v2
      with:
        name: bios-image
        path: bootimage/target/debug/bios.img
        
